### ISSUE TITLE
extent4_type required?

### ISSUE THREAD

**Issue by mgxd** [INCF/BIDS2NDA#1]
Hi,

Error I received after using BIDS2NDA to generate image03:

`Field extent4_type is conditionally required when image_num_dimensions > 3`

Field map scans with 2 encoding directions (AP/PA) are currently [missed](https://github.com/INCF/BIDS2NDA/blob/master/bids2nda/main.py#L181).

**Comment by chrisfilo** [comment]
Those field maps should be split into 3D files. One file per encoding direction.

**Comment by mgxd** [comment]
Ah - I had 4 volumes for each direction, I will split those up then

**Comment by chrisfilo** [comment]
FYI - I tried to clear up the language describing the phase encoding fieldmaps in the spec. Please have a look: https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.fcegd01wpsf8

**Comment by chrisfilo** [comment]
correct link: https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.6gef31kvsx0l
