### ISSUE TITLE
interview_age in months

### ISSUE THREAD

**Issue by mgxd** [INCF/BIDS2NDA#3]

**Comment by chrisfilo** [comment]
Could you elaborate?

**Comment by mgxd** [comment]
the interview age is in months, not years. This is a little tricky with bids' participants.tsv since it just tracks months by increments of 12 essentially

**Comment by chrisfilo** [comment]
The BIDS spec currently does make any claims about the definition of age
and the units it could be expressed in.

**Comment by mgxd** [comment]
> Age should be given as the number of years since birth at the time of scanning (or first scan in case of multi session datasets). Using higher accuracy (weeks) should be avoided due to privacy protection.

In any case, should we multiple the age by 12 to (roughly) give ages in months?

**Comment by chrisfilo** [comment]
My bad! I forgot about it - the multiplication strategy seems the best
option.

On Wed, Jul 13, 2016 at 2:42 PM, Mathias Goncalves <notifications@github.com

**Comment by chrisfilo** [comment]
I'll modify the tool to assume age in years (as in the BIDS spec) and perform this multiplication automatically.
