### ISSUE TITLE
bvek_bval_files column

### ISSUE THREAD

**Issue by mgxd** [INCF/BIDS2NDA#4]
new addition to image03, Y/N string if bvecs/bvals are included with diffusion imaging

**Comment by chrisfilo** [comment]
Is it really called `bvek_bval_ciles`???

**Comment by mgxd** [comment]
haha yes, with a hard 'k'

**Comment by chrisfilo** [comment]
FYI - I've sent an email to NDA asking to correct the typo.

**Comment by chrisfilo** [comment]
Reply from NDA:

> Sveta Novikova (HELP DESK )
> Jan 18, 1:00 PM EST
> 
> Hi Chris,
> element_name is meaningless. The Description is the way to specify the variable.
> Thank you,
> Sveta
